### ISSUE TITLE
Problems with height adjustment

### ISSUE THREAD

**Issue by kalositvan1** [muon-rw/Medieval-Origins-Revival-Forge#1]
Hi!

I made a modpack with around 25 mods, and I wanted to chose Pixie as my origin. For some reason, my FPS camera doesn't adjust my eye height to the Pixie's eyesight. When I crouch however, it works just fine.

Does anyone know what could be the problem?

[Me in TPS](https://github.com/muon-rw/Medieval-Origins-Revival-Forge/assets/148967702/ecf032c7-0568-4540-b1fe-fdda40df3a22)
[Me in FPS while crouching](https://github.com/muon-rw/Medieval-Origins-Revival-Forge/assets/148967702/09ec07d6-7033-498a-99fe-9f14d15ec81b)
[Me in FPS while not crouching](https://github.com/muon-rw/Medieval-Origins-Revival-Forge/assets/148967702/9e8f14be-4c17-4a4f-bca5-405ea8770a37)
[Mods](https://github.com/muon-rw/Medieval-Origins-Revival-Forge/assets/148967702/4813fa35-4456-4329-a569-ff4f91436e32)

**Comment by muon-rw** [comment]
Caused by old versions of Citadel/Alex Caves interfering with Pehkui
